import "server-only";
import { cached } from "@/infra/cache/cache";
import { logger } from "@/infra/log/logger";
import { AppError } from "@/core/errors";
import { canonicalUrl, thumbUrl } from "./url";

const log = logger("youtube:metadata");

export type CaptionTrack = {
  lang: string;
  name: string;
  baseUrl: string;
  /** auto-generated by YouTube's ASR — always in the spoken language */
  auto: boolean;
};

export type VideoMetadata = {
  videoId: string;
  title: string;
  channel: string;
  thumbnailUrl: string;
  durationSec: number;
  description: string;
  keywords: string[];
  captionTracks: CaptionTrack[];
  /** which transport produced the player data */
  source: string;
};

const UA =
  "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0 Safari/537.36";

/** Public InnerTube key — the same one youtube.com ships in its own HTML. */
const INNERTUBE_KEY = "AIzaSyAO_FJ2SlqU8Q4STEHLGCilw_Y9_11qcW8";

/**
 * Player clients, in preference order.
 *
 * The plain watch page no longer hands out usable timed-text URLs (they return
 * an empty body without a proof-of-origin token), but the mobile player
 * endpoints still do — and they need no API key of our own. iOS is first
 * because it serves JSON3 directly; Android is kept as a fallback and returns
 * SRV3 XML, which the caption parser also understands.
 */
const CLIENTS = [
  {
    id: "ios",
    context: {
      clientName: "IOS",
      clientVersion: "20.10.4",
      deviceModel: "iPhone16,2",
      hl: "en",
    },
    headers: {
      "user-agent":
        "com.google.ios.youtube/20.10.4 (iPhone16,2; U; CPU iOS 18_3_2 like Mac OS X)",
    },
  },
  {
    id: "android",
    context: {
      clientName: "ANDROID",
      clientVersion: "20.10.38",
      androidSdkVersion: 30,
      hl: "en",
    },
    headers: {
      "user-agent": "com.google.android.youtube/20.10.38 (Linux; U; Android 11) gzip",
    },
  },
] as const;

/**
 * Real metadata + caption index. No API key and no download required.
 * oEmbed supplies an authoritative title/channel/thumbnail; the player
 * endpoint supplies duration, description, keywords and caption tracks.
 */
export async function fetchMetadata(videoId: string): Promise<VideoMetadata> {
  return cached(`yt:meta:${videoId}`, 10 * 60_000, async () => {
    const [oembedResult, playerResult] = await Promise.allSettled([
      fetchOembed(videoId),
      fetchPlayer(videoId),
    ]);

    // A hard "unavailable" from either source is authoritative — surface it.
    if (oembedResult.status === "rejected" && oembedResult.reason instanceof AppError) {
      throw oembedResult.reason;
    }

    const o = oembedResult.status === "fulfilled" ? oembedResult.value : null;
    const p = playerResult.status === "fulfilled" ? playerResult.value : null;

    if (!o && !p) {
      throw new AppError(
        "Could not reach YouTube for this video. Check the link is public and try again.",
        502,
        "youtube_unavailable",
      );
    }

    if (p?.unplayable && !o) {
      throw new AppError(
        `YouTube refused this video: ${p.unplayable}. Private, age-restricted and members-only videos cannot be processed.`,
        422,
        "video_unavailable",
      );
    }

    const meta: VideoMetadata = {
      videoId,
      title: o?.title ?? p?.title ?? "Untitled video",
      channel: o?.author ?? p?.author ?? "Unknown channel",
      thumbnailUrl: o?.thumbnail ?? thumbUrl(videoId),
      durationSec: p?.durationSec ?? 0,
      description: p?.description ?? "",
      keywords: p?.keywords ?? [],
      captionTracks: p?.captionTracks ?? [],
      source: p?.source ?? "oembed",
    };

    log.info("metadata resolved", {
      videoId,
      source: meta.source,
      captions: meta.captionTracks.length,
      durationSec: meta.durationSec,
    });

    return meta;
  });
}

async function fetchOembed(videoId: string) {
  const res = await fetch(
    `https://www.youtube.com/oembed?url=${encodeURIComponent(canonicalUrl(videoId))}&format=json`,
    { headers: { "user-agent": UA }, signal: AbortSignal.timeout(10_000) },
  );
  if (res.status === 404 || res.status === 401) {
    throw new AppError(
      "That video is private, deleted, or unavailable in this region.",
      422,
      "video_unavailable",
    );
  }
  if (!res.ok) throw new Error(`oembed ${res.status}`);
  const json = (await res.json()) as {
    title: string;
    author_name: string;
    thumbnail_url: string;
  };
  return { title: json.title, author: json.author_name, thumbnail: json.thumbnail_url };
}

type PlayerData = {
  title: string;
  author: string;
  durationSec: number;
  description: string;
  keywords: string[];
  captionTracks: CaptionTrack[];
  unplayable: string | null;
  source: string;
};

/** Tries each player client in turn; the first one that plays back wins. */
async function fetchPlayer(videoId: string): Promise<PlayerData> {
  let lastReason: string | null = null;

  for (const client of CLIENTS) {
    try {
      const res = await fetch(
        `https://www.youtube.com/youtubei/v1/player?key=${INNERTUBE_KEY}&prettyPrint=false`,
        {
          method: "POST",
          headers: { "content-type": "application/json", ...client.headers },
          body: JSON.stringify({
            videoId,
            contentCheckOk: true,
            racyCheckOk: true,
            context: { client: client.context },
          }),
          signal: AbortSignal.timeout(15_000),
        },
      );
      if (!res.ok) {
        lastReason = `http ${res.status}`;
        continue;
      }

      const json = (await res.json()) as Record<string, unknown>;
      const status = json.playabilityStatus as Record<string, unknown> | undefined;
      const details = json.videoDetails as Record<string, unknown> | undefined;

      if (status && status.status !== "OK") {
        lastReason = String(status.reason ?? status.status);
        continue;
      }
      if (!details) {
        lastReason = "no videoDetails";
        continue;
      }

      const tracks = (
        ((json.captions as Record<string, Record<string, unknown[]>> | undefined)?.
          playerCaptionsTracklistRenderer?.captionTracks as
          | Record<string, unknown>[]
          | undefined) ?? []
      )
        .map((t) => ({
          lang: String(t.languageCode ?? "en"),
          name: String((t.name as { simpleText?: string; runs?: { text: string }[] })?.simpleText ??
            (t.name as { runs?: { text: string }[] })?.runs?.[0]?.text ??
            t.languageCode ??
            "auto"),
          baseUrl: String(t.baseUrl ?? ""),
          auto: String(t.kind ?? "") === "asr",
        }))
        .filter((t) => t.baseUrl);

      return {
        title: String(details.title ?? ""),
        author: String(details.author ?? ""),
        durationSec: Number(details.lengthSeconds ?? 0),
        description: String(details.shortDescription ?? ""),
        keywords: (details.keywords as string[] | undefined) ?? [],
        captionTracks: tracks,
        unplayable: null,
        source: `innertube:${client.id}`,
      };
    } catch (err) {
      lastReason = String(err).slice(0, 120);
    }
  }

  // Last resort: scrape the watch page. Its caption URLs usually will not
  // fetch, but its metadata is still accurate.
  try {
    return await fetchWatchPage(videoId);
  } catch {
    throw new Error(`all player clients failed (${lastReason ?? "unknown"})`);
  }
}

async function fetchWatchPage(videoId: string): Promise<PlayerData> {
  const res = await fetch(canonicalUrl(videoId), {
    headers: { "user-agent": UA, "accept-language": "en-US,en;q=0.9" },
    signal: AbortSignal.timeout(15_000),
  });
  if (!res.ok) throw new Error(`watch ${res.status}`);

  const player = extractJson(await res.text(), "ytInitialPlayerResponse");
  if (!player) throw new Error("player response not found");

  const details = player.videoDetails as Record<string, unknown> | undefined;
  const status = player.playabilityStatus as Record<string, unknown> | undefined;

  return {
    title: details ? String(details.title ?? "") : "",
    author: details ? String(details.author ?? "") : "",
    durationSec: details ? Number(details.lengthSeconds ?? 0) : 0,
    description: details ? String(details.shortDescription ?? "") : "",
    keywords: (details?.keywords as string[] | undefined) ?? [],
    captionTracks: [],
    unplayable:
      status && status.status !== "OK" ? String(status.reason ?? status.status) : null,
    source: "watch-page",
  };
}

/** Extracts `var NAME = {...};` from an HTML blob using brace matching. */
function extractJson(html: string, name: string): Record<string, unknown> | null {
  const marker = html.indexOf(`${name} = `);
  if (marker === -1) return null;
  const start = html.indexOf("{", marker);
  if (start === -1) return null;

  let depth = 0;
  let inString = false;
  let escaped = false;
  for (let i = start; i < html.length; i++) {
    const ch = html[i];
    if (inString) {
      if (escaped) escaped = false;
      else if (ch === "\\") escaped = true;
      else if (ch === '"') inString = false;
      continue;
    }
    if (ch === '"') inString = true;
    else if (ch === "{") depth++;
    else if (ch === "}") {
      depth--;
      if (depth === 0) {
        try {
          return JSON.parse(html.slice(start, i + 1)) as Record<string, unknown>;
        } catch {
          return null;
        }
      }
    }
  }
  return null;
}
